from . import fleet_vehicle
from . import hr_employee
from . import res_partner
from . import fleet_vehicle_history
from . import fleet_trip_request
from . import fleet_vehicle_assignment
from . import fleet_fuel_request
from . import fleet_fuel_issue
from . import fleet_maintenance_request
from . import fleet_maintenance_service
